#!/usr/bin/env node
var fs = require('fs'),
  GitHook = require('../src/git-hooks'),
  args = process.argv.slice(2);
  hookName = __filename.split(/[\\/]/).pop();

GitHook.get(hookName)
  .then(function(hooks) {
      var text = fs.readFileSync(args[0], "utf8");
      for(var i=0, l=hooks.length; i < l; i++) {
          text = GitHook.run({
              type : hookName,
              name : hooks[i],
              args : [text]
          });
          fs.writeFileSync(args[0], text);
      }
      process.exit(0);
  });
