#!/usr/bin/env node
var fs = require('fs'),
  colors = require('colors'),
  GitHook = require('../src/git-hooks'),
  args = process.argv.slice(2);
  hookName = __filename.split(/[\\/]/).pop();

GitHook.get(hookName)
.then(function(hooks) {
    var text = fs.readFileSync(args[0], "utf8");
    for(var i=0, l=hooks.length; i < l; i++) {
      try{
        text = GitHook.run({
            type : hookName,
            name : hooks[i],
            args : [text]
        });
      } catch(e) {
        process.exit(1);
      }
      fs.writeFileSync(args[0], text);
    }
    process.exit(0);
});
