#!/usr/bin/env node
var fs = require('fs'),
  GitHook = require('../src/git-hooks'),
  args = process.argv.slice(2);
  hookName = __filename.split(/[\\/]/).pop();


GitHook.get(hookName)
.then(function(hooks) {
    for(var i=0, l=hooks.length; i < l; i++) {
      try{
        result = GitHook.run({
            type : hookName,
            name : hooks[i],
            args : args
        });
      } catch(e) {
        process.exit(1);
      }
    }
    process.exit(0);
});


